# Generated by Django 3.2.2 on 2021-05-14 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0010_alter_orders_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 14)),
        ),
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.TimeField(default=datetime.time(18, 29, 15, 906707)),
        ),
    ]
