# Generated by Django 3.2.2 on 2021-05-14 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0011_auto_20210514_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.TimeField(default=datetime.time(21, 20, 38, 919369)),
        ),
    ]
