# Generated by Django 3.2.2 on 2021-05-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0013_auto_20210515_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
