# Generated by Django 3.2.2 on 2021-05-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Restaurant', '0014_auto_20210515_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.address'),
            preserve_default=False,
        ),
    ]
