# Generated by Django 3.2.2 on 2021-05-15 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Home', '0015_delivery_password'),
        ('Restaurant', '0016_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=500)),
                ('quantity', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery', models.CharField(blank=True, max_length=6, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('food_is_being_prepared', models.BooleanField(default=False)),
                ('ready_for_delivery', models.BooleanField(default=False)),
                ('picked_up', models.BooleanField(default=False)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.address')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.user')),
            ],
        ),
    ]
