# Generated by Django 3.2.2 on 2021-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0017_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
