# Generated by Django 3.2 on 2021-05-19 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0018_auto_20210515_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_quality', models.CharField(max_length=15)),
                ('order_accuracy', models.CharField(max_length=15)),
                ('packaging', models.CharField(max_length=15)),
                ('feedback', models.CharField(max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.orders', unique=True)),
            ],
        ),
    ]
