# Generated by Django 3.2 on 2021-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0019_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
