# Generated by Django 3.2.2 on 2021-05-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
