# Generated by Django 3.2.2 on 2021-05-10 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Query',
        ),
    ]
