# Generated by Django 3.2.2 on 2021-05-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
