# Generated by Django 3.2.2 on 2021-05-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_delete_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.CharField(max_length=6)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('restaurant_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('restaurant_contact', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('cost_for_two', models.DecimalField(decimal_places=2, max_digits=5)),
                ('outlets', models.IntegerField()),
                ('cuisine', models.CharField(max_length=100)),
                ('working_days', models.CharField(max_length=100)),
                ('shop_license', models.FileField(upload_to='')),
                ('fssai', models.FileField(upload_to='')),
                ('gstin_pan', models.FileField(upload_to='')),
                ('menu', models.FileField(upload_to='')),
                ('facade', models.ImageField(upload_to='')),
                ('kitchen', models.ImageField(upload_to='')),
                ('dining_packaging', models.ImageField(upload_to='')),
                ('locality', models.ImageField(upload_to='')),
            ],
        ),
    ]
