# Generated by Django 3.2.2 on 2021-05-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20210511_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.BinaryField(default=False),
        ),
    ]
