# Generated by Django 3.2.2 on 2021-05-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_restaurant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='status',
        ),
    ]
