# Generated by Django 3.2.2 on 2021-05-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_restaurant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
