# Generated by Django 3.2.2 on 2021-05-11 11:54

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_restaurant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='dining_packaging',
            field=models.ImageField(upload_to=Home.models.dining_packaging_directory_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='facade',
            field=models.ImageField(upload_to=Home.models.facade_directory_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='fssai',
            field=models.FileField(upload_to=Home.models.fssai_directory_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='gstin_pan',
            field=models.FileField(upload_to=Home.models.gstin_pan_directory_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='kitchen',
            field=models.ImageField(upload_to=Home.models.kitchen_directory_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='locality',
            field=models.ImageField(upload_to=Home.models.locality_directory_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.FileField(upload_to=Home.models.menu_directory_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='shop_license',
            field=models.FileField(upload_to=Home.models.shop_license_directory_path),
        ),
    ]
