# Generated by Django 3.2.2 on 2021-05-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
