# Generated by Django 3.2.2 on 2021-05-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='password',
            field=models.CharField(default='abcde1234', max_length=10),
            preserve_default=False,
        ),
    ]
